# Generated by Django 6.0.4 on 2026-05-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=8, unique=True)),
                ('length', models.PositiveIntegerField()),
            ],
        ),
    ]
