# Generated by Django 6.0.4 on 2026-05-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0002_allowedword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='term',
            name='word',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
