# Generated by Django 6.0.4 on 2026-05-22 22:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0003_alter_game_id_alter_term_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allowedword',
            name='word',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='word',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
